#spring.application.name=localizacao
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring:
  application:
    name: localizacao
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
    properties:
      hibernate:
        format_sql: true
